# Generated by Django 3.1.1 on 2020-12-23 18:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, primary_key=True, serialize=False)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('about', models.TextField()),
                ('achievements', models.TextField()),
                ('mail', models.EmailField(blank=True, max_length=254, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('github', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='President',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('github', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profile_photo/')),
                ('committee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='committees.committee')),
            ],
        ),
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo1', models.ImageField(blank=True, upload_to='clubphotos/')),
                ('photo2', models.ImageField(blank=True, upload_to='clubphotos/')),
                ('photo3', models.ImageField(blank=True, upload_to='clubphotos/')),
                ('photo4', models.ImageField(blank=True, upload_to='clubphotos/')),
                ('photo5', models.ImageField(blank=True, upload_to='clubphotos/')),
                ('photo6', models.ImageField(blank=True, upload_to='clubphotos/')),
                ('photo7', models.ImageField(blank=True, upload_to='clubphotos/')),
                ('photo8', models.ImageField(blank=True, upload_to='clubphotos/')),
                ('photo9', models.ImageField(blank=True, upload_to='clubphotos/')),
                ('committee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='committees.committee')),
            ],
        ),
        migrations.CreateModel(
            name='CommitteeEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='committees.committee')),
            ],
        ),
        migrations.CreateModel(
            name='CommitteeAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('committee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='committees.committee')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CarouselPhotos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo1', models.ImageField(blank=True, upload_to='carouselphotos/')),
                ('photo2', models.ImageField(blank=True, upload_to='carouselphotos/')),
                ('photo3', models.ImageField(blank=True, upload_to='carouselphotos/')),
                ('committee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='committees.committee')),
            ],
        ),
    ]
