# Generated by Django 3.1.1 on 2020-12-23 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('committees', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='committee',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='committee',
            name='github',
        ),
        migrations.RemoveField(
            model_name='committee',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='committee',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='committee',
            name='twitter',
        ),
    ]
