# Generated by Django 3.1.1 on 2020-12-23 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('committees', '0002_auto_20201224_0006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='committee',
            name='achievements',
        ),
    ]
