# Generated by Django 3.1.1 on 2020-12-23 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committees', '0003_remove_committee_achievements'),
    ]

    operations = [
        migrations.AddField(
            model_name='committeeevent',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
    ]
