# Generated by Django 3.1.1 on 2020-12-24 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('committees', '0004_committeeevent_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current', models.FileField(blank=True, upload_to='csv/')),
                ('past', models.FileField(blank=True, upload_to='csv/')),
                ('committee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='committees.committee')),
            ],
        ),
    ]
