# Generated by Django 3.1.1 on 2020-12-25 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('committees', '0005_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='PIC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profile_photo/')),
                ('url', models.URLField()),
                ('committee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='committees.committee')),
            ],
        ),
    ]
