# Generated by Django 3.1.1 on 2020-12-30 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('committees', '0010_auto_20201227_1531'),
    ]

    operations = [
        migrations.CreateModel(
            name='VicePresident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('github', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profile_photo/')),
                ('committee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='committees.committee')),
            ],
        ),
    ]
