# Generated by Django 3.1.1 on 2021-01-10 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committees', '0012_committee_achievement'),
    ]

    operations = [
        migrations.AddField(
            model_name='pic',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
