# Generated by Django 3.1.1 on 2021-02-12 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committees', '0013_pic_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='committeeevent',
            name='event_type',
            field=models.CharField(choices=[('Past', 'Past'), ('Present', 'Present'), ('Future', 'Future')], default='Past', max_length=255),
        ),
    ]
