# Generated by Django 3.1.1 on 2021-02-12 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committees', '0014_committeeevent_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='committeeevent',
            name='present_event',
            field=models.BooleanField(default=False),
        ),
    ]
