# Generated by Django 3.1.1 on 2021-02-12 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('committees', '0015_committeeevent_present_event'),
    ]

    operations = [
        migrations.RenameField(
            model_name='committeeevent',
            old_name='present_event',
            new_name='upcoming',
        ),
        migrations.RemoveField(
            model_name='committeeevent',
            name='event_type',
        ),
    ]
