# Generated by Django 3.1.1 on 2021-01-09 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_update_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='update',
            name='youtube',
            field=models.URLField(blank=True, null=True),
        ),
    ]
