# Generated by Django 3.1.1 on 2021-01-09 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_update_youtube'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update',
            name='youtube',
            field=models.TextField(blank=True, null=True),
        ),
    ]
