# Generated by Django 3.1.1 on 2020-12-23 15:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, primary_key=True, serialize=False)),
                ('about', models.TextField()),
                ('achievements', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo1', models.ImageField(blank=True, upload_to='clubphotos/')),
                ('photo2', models.ImageField(blank=True, upload_to='clubphotos/')),
                ('photo3', models.ImageField(blank=True, upload_to='clubphotos/')),
                ('photo4', models.ImageField(blank=True, upload_to='clubphotos/')),
                ('photo5', models.ImageField(blank=True, upload_to='clubphotos/')),
                ('photo6', models.ImageField(blank=True, upload_to='clubphotos/')),
                ('photo7', models.ImageField(blank=True, upload_to='clubphotos/')),
                ('photo8', models.ImageField(blank=True, upload_to='clubphotos/')),
                ('photo9', models.ImageField(blank=True, upload_to='clubphotos/')),
                ('club', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='clubs.club')),
            ],
        ),
        migrations.CreateModel(
            name='PageAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='clubs.club')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClubEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.club')),
            ],
        ),
    ]
