# Generated by Django 3.1.1 on 2020-12-23 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselPhotos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo1', models.ImageField(blank=True, upload_to='carouselphotos/')),
                ('photo2', models.ImageField(blank=True, upload_to='carouselphotos/')),
                ('photo3', models.ImageField(blank=True, upload_to='carouselphotos/')),
                ('club', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='clubs.club')),
            ],
        ),
    ]
