# Generated by Django 3.1.1 on 2020-12-23 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_carouselphotos'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='facebook',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='club',
            name='github',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='club',
            name='instagram',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='club',
            name='linkedin',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='club',
            name='mail',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='club',
            name='twitter',
            field=models.URLField(null=True),
        ),
    ]
