# Generated by Django 3.1.1 on 2020-12-23 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0006_jointsecretary_secretary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jointsecretary',
            name='club',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='clubs.club'),
        ),
        migrations.AlterField(
            model_name='secretary',
            name='club',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='clubs.club'),
        ),
    ]
