# Generated by Django 3.1.1 on 2020-12-23 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0007_auto_20201223_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='jointsecretary',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photo/'),
        ),
        migrations.AddField(
            model_name='secretary',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photo/'),
        ),
    ]
