# Generated by Django 3.1.1 on 2020-12-23 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('committees', '0001_initial'),
        ('clubs', '0008_auto_20201223_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='committee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='committees.committee'),
        ),
    ]
