# Generated by Django 3.1.1 on 2020-12-25 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0009_club_committee'),
    ]

    operations = [
        migrations.AddField(
            model_name='photos',
            name='caption1',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='photos',
            name='caption2',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='photos',
            name='caption3',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='photos',
            name='caption4',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='photos',
            name='caption5',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='photos',
            name='caption6',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='photos',
            name='caption7',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='photos',
            name='caption8',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='photos',
            name='caption9',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
