# Generated by Django 3.1.1 on 2020-12-29 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0013_auto_20201227_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='dribble',
            field=models.URLField(blank=True, null=True),
        ),
    ]
