# Generated by Django 3.1.1 on 2020-12-29 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0014_club_dribble'),
    ]

    operations = [
        migrations.AddField(
            model_name='jointsecretary',
            name='dribble',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='secretary',
            name='dribble',
            field=models.URLField(blank=True, null=True),
        ),
    ]
