# Generated by Django 3.1.1 on 2020-12-30 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0015_auto_20201229_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='youtube',
            field=models.URLField(blank=True, null=True),
        ),
    ]
