# Generated by Django 3.1.1 on 2021-01-12 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0016_club_youtube'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='curr',
            field=models.FileField(blank=True, null=True, upload_to='csv/'),
        ),
    ]
