# Generated by Django 3.1.1 on 2021-02-12 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0017_members_curr'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubevent',
            name='upcoming',
            field=models.BooleanField(default=False),
        ),
    ]
