# Generated by Django 3.1.1 on 2021-05-24 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0018_clubevent_upcoming'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='achievements',
            field=models.TextField(blank=True, null=True),
        ),
    ]
