# Generated by Django 3.1.1 on 2021-08-27 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0020_auto_20210827_1345'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='calendarevent',
            name='check_start_date',
        ),
    ]
