# Generated by Django 3.1.1 on 2021-08-27 13:52

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0021_auto_20210827_1347'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='calendarevent',
            constraint=models.CheckConstraint(check=models.Q(end_date__gte=django.db.models.expressions.F('start_date')), name='check_start_date'),
        ),
    ]
