# Generated by Django 3.1.1 on 2020-12-25 14:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Festival',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, primary_key=True, serialize=False)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('about', models.TextField()),
                ('events', models.TextField()),
                ('mail', models.EmailField(blank=True, max_length=254, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('github', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo1', models.ImageField(blank=True, upload_to='clubphotos/')),
                ('caption1', models.CharField(max_length=255, null=True)),
                ('photo2', models.ImageField(blank=True, upload_to='clubphotos/')),
                ('caption2', models.CharField(max_length=255, null=True)),
                ('photo3', models.ImageField(blank=True, upload_to='clubphotos/')),
                ('caption3', models.CharField(max_length=255, null=True)),
                ('photo4', models.ImageField(blank=True, upload_to='clubphotos/')),
                ('caption4', models.CharField(max_length=255, null=True)),
                ('photo5', models.ImageField(blank=True, upload_to='clubphotos/')),
                ('caption5', models.CharField(max_length=255, null=True)),
                ('photo6', models.ImageField(blank=True, upload_to='clubphotos/')),
                ('caption6', models.CharField(max_length=255, null=True)),
                ('photo7', models.ImageField(blank=True, upload_to='clubphotos/')),
                ('caption7', models.CharField(max_length=255, null=True)),
                ('photo8', models.ImageField(blank=True, upload_to='clubphotos/')),
                ('caption8', models.CharField(max_length=255, null=True)),
                ('photo9', models.ImageField(blank=True, upload_to='clubphotos/')),
                ('caption9', models.CharField(max_length=255, null=True)),
                ('fest', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='festivals.festival')),
            ],
        ),
        migrations.CreateModel(
            name='FestAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fest', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='festivals.festival')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CarouselPhotos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo1', models.ImageField(blank=True, upload_to='carouselphotos/')),
                ('photo2', models.ImageField(blank=True, upload_to='carouselphotos/')),
                ('photo3', models.ImageField(blank=True, upload_to='carouselphotos/')),
                ('fest', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='festivals.festival')),
            ],
        ),
    ]
