# Generated by Django 3.1.1 on 2020-12-25 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festivals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='festival',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
