# Generated by Django 3.1.1 on 2021-08-27 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('committees', '0016_auto_20210212_1539'),
        ('festivals', '0003_auto_20201227_1531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='festival',
            name='user',
        ),
        migrations.AddField(
            model_name='festival',
            name='committee',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='committees.committee'),
        ),
    ]
